name: Metrics

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          base_hireable: yes
          config_timezone: America/Bogota
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_calendar: yes
          plugin_repositories: yes
          plugin_repositories_featured: personal_website, spacecraft
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: cmake, html, shell, css, text
          plugin_languages_limit: 3
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: labels
          plugin_topics_sort: stars

  medias:
    runs-on: ubuntu-latest
    steps:
      - name: Medias
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: NOT_NEEDED
          base: ""
          base_hireable: yes
          config_timezone: America/Bogota
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://arcibyte.vercel.app
